<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_offUs Limit_Bifast</name>
   <tag></tag>
   <elementGuidId>23b46b48-458f-47bc-bd53-52f748553c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id=''])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;transferBifast&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>085bba7b-80fd-4c8c-8fb9-611c797d3ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b0d17bf6-3f37-4da0-9d09-97f1718916ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9a17805-674c-484e-a59b-0b4e43868c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transferBifast</value>
      <webElementGuid>737b28a3-2cbe-4d03-b73b-619e3dd13de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>100.000</value>
      <webElementGuid>02268446-caab-4042-ae8e-df81f892d1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6888e959-0cb0-4677-965b-eb50d7408810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedStart css-1ixds2g</value>
      <webElementGuid>7ee76b28-4421-4b19-ab60-80661ba4a4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>250.000.000</value>
      <webElementGuid>de4df6f9-7c5e-42df-bafc-67a4615d5430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiScopedCssBaseline-root css-y57rlh&quot;]/div[@class=&quot;MuiBox-root css-k008qs&quot;]/main[@class=&quot;MuiBox-root css-jmbm5p&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-gutters MuiToolbar-regular css-i6s8oy&quot;]/div[@class=&quot;css-1v8gcgw&quot;]/form[1]/div[@class=&quot;css-1cbyj93&quot;]/div[@class=&quot;css-195o3zf&quot;]/div[1]/div[@class=&quot;MuiBox-root css-1xaekgw&quot;]/div[@class=&quot;css-1lq7se8&quot;]/div[@class=&quot;css-1v8gcgw&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root a-input-text sm currents css-a0vqr6&quot;]/div[@class=&quot;MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary Mui-focused MuiInputBase-formControl MuiInputBase-adornedStart css-16z2xte&quot;]/input[@class=&quot;MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedStart css-1ixds2g&quot;]</value>
      <webElementGuid>2304d0b6-9087-4f7f-8f30-3435bb079900</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id=''])[7]</value>
      <webElementGuid>344b4b1b-8c17-40e4-aa55-e0c1f0271a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div/form/div/div[2]/div/div[5]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>81128280-c903-4923-ae34-6062945242fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>f56a718c-5158-4cdd-a4dc-d88552c97cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'transferBifast' and @placeholder = '100.000' and @type = 'text']</value>
      <webElementGuid>a07f8414-3c64-4b8c-973e-5d7fd06f230d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
