<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_offUs Limit_online</name>
   <tag></tag>
   <elementGuidId>4db0f040-43db-4652-a497-c23ce0911ce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'online' and @placeholder = '100.000' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id=''])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;online&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6baac450-a1c3-4337-9847-3adf584d2972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>48d3b59c-d48d-474f-8194-077db2bed7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5eb1ee49-93b5-43b6-a753-3ff0fc7861a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>online</value>
      <webElementGuid>af77cff9-dfb6-4c63-9712-9766e3142035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>100.000</value>
      <webElementGuid>038204fa-1906-43de-b63e-5163f3c7127d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f61bd245-c43e-4e0a-b59c-40b8d116e1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedStart css-1ixds2g</value>
      <webElementGuid>e20d55b3-8dd6-4283-9195-61e88ac3fb37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>50.000.000</value>
      <webElementGuid>d70459fa-6d51-4c5d-85da-d766e53ae86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiScopedCssBaseline-root css-y57rlh&quot;]/div[@class=&quot;MuiBox-root css-k008qs&quot;]/main[@class=&quot;MuiBox-root css-jmbm5p&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-gutters MuiToolbar-regular css-i6s8oy&quot;]/div[@class=&quot;css-1v8gcgw&quot;]/form[1]/div[@class=&quot;css-1cbyj93&quot;]/div[@class=&quot;css-195o3zf&quot;]/div[1]/div[@class=&quot;MuiBox-root css-1xaekgw&quot;]/div[@class=&quot;css-1lq7se8&quot;]/div[@class=&quot;css-1v8gcgw&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root a-input-text sm currents css-a0vqr6&quot;]/div[@class=&quot;MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary Mui-focused MuiInputBase-formControl MuiInputBase-adornedStart css-16z2xte&quot;]/input[@class=&quot;MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedStart css-1ixds2g&quot;]</value>
      <webElementGuid>107e722e-0aa2-4668-822d-e1de45bafce1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id=''])[4]</value>
      <webElementGuid>c9bea5d8-a7b2-4c32-8c3c-a65f2602b690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div/form/div/div[2]/div/div[5]/div[2]/div/div/div/input</value>
      <webElementGuid>ad567a69-6591-4bdf-a19a-e12850314100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>c8467f1c-6d0b-44c7-ad1b-d2e6977f9529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'online' and @placeholder = '100.000' and @type = 'text']</value>
      <webElementGuid>f5079751-4678-48ea-aedc-a64366de72e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
