<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_offUs Limit_rtgs</name>
   <tag></tag>
   <elementGuidId>eecd633b-4078-410c-a316-fb5bd9f27185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'rtgs' and @placeholder = '100.000' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id=''])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;rtgs&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b130201f-5281-4bfd-be1a-7a161f5af7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>60fbcbec-a41d-43cf-9e4f-f61c000ff59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2423ec99-fc1b-4d6a-bc93-d90067c91f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rtgs</value>
      <webElementGuid>5bd78314-39d3-4614-8f1b-6d8599b096f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>100.000</value>
      <webElementGuid>9f3b5129-5765-4583-b2d6-50ca5e382d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8b12c6a-cfcd-4384-8af7-60c7eb2e1223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedStart css-1ixds2g</value>
      <webElementGuid>b732095f-0013-4807-a22f-17fcaf3af7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1.000.000.000</value>
      <webElementGuid>06150444-0b61-434d-9e5d-25a073c44db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiScopedCssBaseline-root css-y57rlh&quot;]/div[@class=&quot;MuiBox-root css-k008qs&quot;]/main[@class=&quot;MuiBox-root css-jmbm5p&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-gutters MuiToolbar-regular css-i6s8oy&quot;]/div[@class=&quot;css-1v8gcgw&quot;]/form[1]/div[@class=&quot;css-1cbyj93&quot;]/div[@class=&quot;css-195o3zf&quot;]/div[1]/div[@class=&quot;MuiBox-root css-1xaekgw&quot;]/div[@class=&quot;css-1lq7se8&quot;]/div[@class=&quot;css-1v8gcgw&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root a-input-text sm currents css-a0vqr6&quot;]/div[@class=&quot;MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary Mui-focused MuiInputBase-formControl MuiInputBase-adornedStart css-16z2xte&quot;]/input[@class=&quot;MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedStart css-1ixds2g&quot;]</value>
      <webElementGuid>ed6a2d59-dd23-4310-84ee-f2cf84538136</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id=''])[6]</value>
      <webElementGuid>5f477549-1669-40a8-817f-1efa375f95f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div/form/div/div[2]/div/div[5]/div[3]/div/div/div/input</value>
      <webElementGuid>797c0404-476e-4513-97de-40154b14a6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>33331e96-7803-4712-8154-f21239b59657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rtgs' and @placeholder = '100.000' and @type = 'text']</value>
      <webElementGuid>f9b9d42f-702d-49c9-8636-0361002f759a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
