<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_Notif</name>
   <tag></tag>
   <elementGuidId>be9fe2ac-fd37-466e-a1ec-32c3a6488ea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main/div/div/div[2]/div[2]/li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@role = 'menuitem' and (text() = 'Transfer Sesama BTN13/06/2025Rp 1,00Ke IRSALINA SANTI KHASABerhasil' or . = 'Transfer Sesama BTN13/06/2025Rp 1,00Ke IRSALINA SANTI KHASABerhasil')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.MuiButtonBase-root.MuiMenuItem-root.MuiMenuItem-gutters.MuiMenuItem-root.MuiMenuItem-gutters.css-e8l20g</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2e25f68b-bcd2-48cd-9602-9ee0c66f869e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiMenuItem-root MuiMenuItem-gutters MuiMenuItem-root MuiMenuItem-gutters css-e8l20g</value>
      <webElementGuid>8c0466c7-3cff-4df2-b591-23adecedbad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>642b2dac-be8a-46eb-9e6a-fb740a8f2354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>528c82e9-c926-4fe1-a64b-52c38cd37bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transfer Sesama BTN13/06/2025Rp 1,00Ke IRSALINA SANTI KHASABerhasil</value>
      <webElementGuid>fe5f4755-5c13-4af3-bc02-c86d2278098b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiScopedCssBaseline-root css-y57rlh&quot;]/div[@class=&quot;MuiBox-root css-k008qs&quot;]/main[@class=&quot;MuiBox-root css-jmbm5p&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-gutters MuiToolbar-regular css-i6s8oy&quot;]/div[@class=&quot;css-kxkmqf&quot;]/div[@class=&quot;css-fjcsr3&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-1s6owqs&quot;]/li[@class=&quot;MuiButtonBase-root MuiMenuItem-root MuiMenuItem-gutters MuiMenuItem-root MuiMenuItem-gutters css-e8l20g&quot;]</value>
      <webElementGuid>b73e24c1-409e-40aa-a343-f12e90b886de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div/div[2]/div[2]/li</value>
      <webElementGuid>5364e34a-438a-42a4-8075-42763b9c5d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BB'])[2]/following::li[5]</value>
      <webElementGuid>7dfe8d25-0fed-4cd7-881a-376688921188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berhasil'])[2]/preceding::li[1]</value>
      <webElementGuid>ab5354c4-58d9-4193-befb-a93706df753e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div[2]/div[2]/li</value>
      <webElementGuid>e4b3d8c8-8649-4207-b01b-5362683de314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Transfer Sesama BTN13/06/2025Rp 1,00Ke IRSALINA SANTI KHASABerhasil' or . = 'Transfer Sesama BTN13/06/2025Rp 1,00Ke IRSALINA SANTI KHASABerhasil')]</value>
      <webElementGuid>ede83c37-c832-40d8-9ad7-ee47e5e04961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
